#Project Setup
general:
  productiveBranch: master
  defaultNode: ''

#Steps Specific Configuration
steps:
  executeMaven:
    dockerImage: maven:3.5-jdk-8-alpine

  executeNpm:
    dockerImage: s4sdk/docker-node-browsers

  executeGradle:
    dockerImage: gradle:4.0.1-jdk8

  checkFindbugs:
    includeFilterFile: s4hana_findbugs_include_filter.xml

  checkJMeter:
    dockerImage: famiko/jmeter-base
    testPlan: ./performance-tests/*
    reportDirectory: /jmeter-report
    failThreshold: 100
    unstableThreshold: 90

  deployToCfWithCli:
    dockerImage: s4sdk/docker-cf-cli
    smokeTestStatusCode: '200'

#Stage Specific Configurations
stages:
  integrationTests:
    retry: 1
    forkCount: 1C

  checkmarxScan:
    filterPattern: '!**/*.log, !**/*.lock, !**/*.json, !**/*.html, !**/Cx*, **/*.js, **/*.java, **/*.ts'
    fullScansScheduled: false
    generatePdfReport: true
    incremental: true
    preset: '36'
    vulnerabilityThresholdLow: 99999
    vulnerabilityThresholdMedium: 0

  artifactDeployment:
    nexus:
      version: nexus3
